/* Red documental del POT: nodos concretos, hubs por frecuencia y evidencia verificable. */
const PDF='./BOGOTAREVERDE.pdf';
const COLORS={e1:'#2fd4c8',e2:'#6c9cff',e3:'#e6a65a',e4:'#b18aff'};
const STRUCT={e1:'Estructura Ecológica Principal',e2:'Estructura Funcional y del Cuidado',e3:'Estructura Socioeconómica, Creativa y de Innovación',e4:'Estructura Integradora de Patrimonio'};
const nodes=[
 {id:'agua',name:'Agua',cat:'e1',x:300,y:230,size:34,freq:42,desc:'Sistema hídrico y condición de soporte de la EEP.',quote:'“La estructura ecológica principal es la base de la resiliencia climática y de la sostenibilidad ambiental del territorio.”',page:'p. 42',maps:[['Estructura Ecológica Principal','p. 42 · áreas protegidas, sistema hídrico y resiliencia'] ]},
 {id:'humedales',name:'Humedales',cat:'e1',x:180,y:390,size:38,freq:48,desc:'Reservas Distritales de Humedal y ecosistemas concretos.',quote:'“No se podrán realizar obras sobre la ronda hídrica o la zona de fluctuación del nivel de agua.”',page:'p. 186',maps:[['Estructura Ecológica Principal','p. 42 · Reservas Distritales de Humedal'],['Conectores ecosistémicos','p. 60 · Suba–Conejera'] ]},
 {id:'conectores',name:'Conectores ecosistémicos',cat:'e1',x:410,y:395,size:28,freq:28,desc:'Corredores que vinculan áreas de la EEP.',quote:'“Mapa de los conectores ecosistémicos. POT Bogotá Reverdece 2022-2035.”',page:'p. 60',maps:[['Conectores ecosistémicos','p. 60 · Cerros–río Bogotá, Media Luna del Sur, Suba–Conejera, Virrey–Chicó y Fucha'] ]},
 {id:'reserva',name:'Thomas van der Hammen',cat:'e1',x:520,y:175,size:29,freq:24,desc:'Reserva Forestal Regional Productora del Norte de Bogotá.',quote:'“Reserva Forestal Regional Productora del Norte de Bogotá - Thomas van der Hammen.”',page:'p. 42',maps:[['Estructura Ecológica Principal','p. 42 · reserva forestal regional'] ]},
 {id:'transporte',name:'Transporte público',cat:'e2',x:710,y:260,size:42,freq:55,desc:'Red de movilidad y proyectos masivos de transporte.',quote:'“Se busca una ciudad de proximidad donde los tiempos de desplazamiento no superen los treinta minutos en modos de transporte público limpios y sostenibles.”',page:'p. 149',maps:[['Sistema de Movilidad','p. 172 · red Metro, corredores y actuaciones estratégicas'] ]},
 {id:'equipamientos',name:'Equipamientos',cat:'e2',x:820,y:435,size:34,freq:39,desc:'Servicios sociales, educación, salud e integración social.',quote:'“Dotar a la ciudad de equipamientos y servicios sociales (educación, salud, integración social, entre otros) [...] facilitará que los flujos sociales se movilicen en un rango de tiempo de treinta minutos o menos.”',page:'p. 170',maps:[['Manzanas del Cuidado','p. 123 · manzanas activas y proyectadas'] ]},
 {id:'vivienda',name:'Vivienda',cat:'e2',x:610,y:520,size:34,freq:44,desc:'Áreas residenciales y producción del hábitat.',quote:'“La ciudad de proximidad reconoce las diferentes formas de habitar y transitar la ciudad.”',page:'p. 149',maps:[['Ciudad popular','p. 141 · progresión de la ciudad popular e informal'] ]},
 {id:'empleo',name:'Empleo',cat:'e3',x:865,y:150,size:39,freq:51,desc:'Concentración, aglomeración y distribución territorial del trabajo.',quote:'“La dinámica misma de las economías de aglomeración hace que estas se desborden en el territorio y se constituya un modelo policéntrico que puede ser potenciado.”',page:'p. 171',maps:[['Estructura Socioeconómica, Creativa y de Innovación','p. 170 · centros, clústeres y corazones productivos'] ]},
 {id:'corazones',name:'Corazones productivos',cat:'e3',x:1030,y:280,size:31,freq:32,desc:'Aglomeraciones especializadas y diversificadas.',quote:'“Potenciar corazones productivos de aglomeración especializada para concretar el modelo policéntrico.”',page:'p. 171',maps:[['Estructura Socioeconómica, Creativa y de Innovación','p. 170 · corazones productivos'] ]},
 {id:'abastecimiento',name:'Abastecimiento',cat:'e3',x:1010,y:450,size:29,freq:26,desc:'Centros de abastecimiento, plazas y cadenas alimentarias.',quote:'“El POT pretende facilitar y propiciar nuevas fuentes de empleo [...] y desarrollar corazones productivos incipientes y economías de proximidad.”',page:'p. 171',maps:[['Estructura Socioeconómica, Creativa y de Innovación','p. 170 · centros de abastecimiento y plazas de mercado'] ]},
 {id:'patrimonio',name:'Patrimonio',cat:'e4',x:590,y:110,size:32,freq:37,desc:'Estructura integradora de patrimonio material, natural e inmaterial.',quote:'“El patrimonio cultural ha sido la oportunidad para [...] estrechar los lazos con su comunidad.”',page:'p. 126',maps:[['Patrimonio','p. 126 · estructura integradora de patrimonio'] ]},
 {id:'comunidades',name:'Comunidades',cat:'e4',x:420,y:585,size:29,freq:24,desc:'Actores, cuidado, apropiación y construcción colectiva del territorio.',quote:'“La ciudad popular, en su mayoría autoconstruida, representa cerca del 30% del suelo urbano de Bogotá.”',page:'p. 141',maps:[['Ciudad popular','p. 141 · progresión histórica'] ]},
 {id:'cuidado',name:'Cuidado',cat:'e2',x:750,y:590,size:30,freq:33,desc:'Red del cuidado, servicios y proximidad.',quote:'“Con cada UPL abastecida de manera equitativa, próxima y accesible de servicios, Bogotá se convertirá en una ciudad de treinta minutos.”',page:'p. 123',maps:[['Manzanas del Cuidado','p. 123 · localizaciones activas y proyectadas'] ]},
 {id:'regiotram',name:'RegioTram',cat:'e2',x:960,y:595,size:26,freq:19,desc:'Infraestructura regional conectada con áreas estratégicas.',quote:'“Por la zona pasarán [...] el RegioTram de Occidente y la tercera línea del Metro.”',page:'p. 172',maps:[['Sistema de Movilidad','p. 172 · movilidad regional y actuaciones estratégicas'] ]},
 {id:'campus',name:'Campus de Innovación',cat:'e3',x:1110,y:155,size:27,freq:17,desc:'Ámbito de innovación, academia, empresas y sector público.',quote:'“Con el Campus de Innovación se consolidará un modelo de ciudad inteligente que combinará los principales ecosistemas circundantes con las diferentes dinámicas urbanas existentes.”',page:'p. 177',maps:[['Campus de Innovación','p. 177 · plano 1:5000, estaciones Metro L3 y usos'] ]},
 {id:'ruralidad',name:'Ruralidad',cat:'e1',x:170,y:570,size:28,freq:22,desc:'Paisajes sostenibles, agroparques y relaciones regionales.',quote:'“Los paisajes sostenibles son la figura de protección y manejo ambiental [...] en áreas rurales.”',page:'p. 69',maps:[['Paisajes sostenibles','p. 68–69 · agroparques y corredores rurales'] ]}
];
const edges=[
 ['agua','humedales','soporte','directa'],['humedales','conectores','soporte','directa'],['reserva','humedales','soporte','directa'],['humedales','transporte','resiliencia','indirecta'],['agua','resiliencia','resiliencia','directa'],['ruralidad','agua','soporte','directa'],['reserva','patrimonio','soporte','indirecta'],['humedales','patrimonio','soporte','indirecta'],['transporte','vivienda','soporte','directa'],['transporte','empleo','soporte','directa'],['transporte','equipamientos','soporte','directa'],['transporte','cuidado','soporte','directa'],['regiotram','empleo','soporte','directa'],['equipamientos','cuidado','soporte','directa'],['vivienda','cuidado','soporte','directa'],['empleo','corazones','soporte','directa'],['corazones','abastecimiento','soporte','directa'],['abastecimiento','comunidades','soporte','indirecta'],['empleo','campus','soporte','directa'],['campus','transporte','soporte','directa'],['patrimonio','comunidades','soporte','directa'],['comunidades','cuidado','resiliencia','indirecta'],['ruralidad','empleo','soporte','indirecta'],['vivienda','comunidades','soporte','directa'],['equipamientos','empleo','soporte','indirecta'],['transporte','regiotram','soporte','directa'],['conectores','patrimonio','resiliencia','indirecta'],['humedales','cuidado','resiliencia','indirecta']
].map((e,i)=>({id:i,s:e[0],t:e[1],kind:e[2],mode:e[3]}));
const svg=document.getElementById('networkViz'), NS='http://www.w3.org/2000/svg'; let activeFilter='all', selected=null, pan={x:0,y:0,scale:1,drag:false,sx:0,sy:0};
const gEdges=document.createElementNS(NS,'g'),gNodes=document.createElementNS(NS,'g'); svg.append(gEdges,gNodes);
function node(id){return nodes.find(n=>n.id===id)}
function text(parent,x,y,value,cls,anchor='middle'){const t=document.createElementNS(NS,'text');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('text-anchor',anchor);t.setAttribute('class',cls);t.textContent=value;parent.append(t);return t}
function render(){gEdges.innerHTML='';gNodes.innerHTML=''; const visible=n=>activeFilter==='all'||n.cat===activeFilter; edges.forEach(e=>{const s=node(e.s),t=node(e.t),line=document.createElementNS(NS,'line');line.setAttribute('x1',s.x);line.setAttribute('y1',s.y);line.setAttribute('x2',t.x);line.setAttribute('y2',t.y);line.setAttribute('class','edge '+(visible(s)&&visible(t)?'':'dim'));line.setAttribute('stroke',e.kind==='soporte'?'#e6a65a':'#6c9cff');line.setAttribute('stroke-width',e.mode==='directa'?1.7:1.1);if(e.mode!=='directa')line.setAttribute('stroke-dasharray','5 7');line.setAttribute('marker-end','url(#arrow)');line.addEventListener('click',()=>selectEdge(e));gEdges.append(line)});nodes.forEach(n=>{const wrap=document.createElementNS(NS,'g');wrap.setAttribute('class','node '+(visible(n)?'':'dim'));wrap.dataset.id=n.id;const halo=document.createElementNS(NS,'circle');halo.setAttribute('cx',n.x);halo.setAttribute('cy',n.y);halo.setAttribute('r',n.size+12);halo.setAttribute('class','node-halo');halo.setAttribute('fill',COLORS[n.cat]);wrap.append(halo);const c=document.createElementNS(NS,'circle');c.setAttribute('cx',n.x);c.setAttribute('cy',n.y);c.setAttribute('r',n.size);c.setAttribute('class','main-node');c.setAttribute('fill','#0d1619');c.setAttribute('stroke',COLORS[n.cat]);c.style.color=COLORS[n.cat];wrap.append(c);text(wrap,n.x,n.y+4,n.name,'node-label');text(wrap,n.x,n.y+n.size+17,STRUCT[n.cat].replace('Estructura ','').replace('Principal','').replace(', Creativa y de Innovación',''),'node-structure');wrap.addEventListener('click',()=>selectNode(n));gNodes.append(wrap)}); if(!document.getElementById('arrow')){const defs=document.createElementNS(NS,'defs'),m=document.createElementNS(NS,'marker');m.id='arrow';m.setAttribute('viewBox','0 0 10 10');m.setAttribute('refX','9');m.setAttribute('refY','5');m.setAttribute('markerWidth','5');m.setAttribute('markerHeight','5');m.setAttribute('orient','auto-start-reverse');const p=document.createElementNS(NS,'path');p.setAttribute('d','M 0 0 L 10 5 L 0 10 z');p.setAttribute('fill','#9ba8a5');m.append(p);defs.append(m);svg.prepend(defs)}}
function selectNode(n){selected=n;document.getElementById('evidenceTitle').textContent=n.name;document.getElementById('evidenceMeta').textContent=`${STRUCT[n.cat]} · ${n.desc} · ${n.freq} menciones / señales documentales`;document.getElementById('evidenceQuote').textContent=n.quote;document.getElementById('evidenceSource').textContent=`— POT Bogotá Reverdece · ${n.page}`;document.getElementById('mapList').innerHTML=n.maps.map(m=>`<div class="map-card"><div><strong>${m[0]}</strong><span>${m[1]}</span></div><a href="${PDF}" target="_blank">Abrir ↗</a></div>`).join('');document.querySelectorAll('.main-node').forEach(c=>c.classList.remove('focus-ring'));const current=[...document.querySelectorAll('.node')].find(x=>x.dataset.id===n.id);if(current)current.querySelector('.main-node').classList.add('focus-ring');document.getElementById('evidencia').scrollIntoView({behavior:'smooth',block:'nearest'})}
function selectEdge(e){const s=node(e.s),t=node(e.t);document.getElementById('evidenceTitle').textContent=`${s.name} ↔ ${t.name}`;document.getElementById('evidenceMeta').textContent=`Relación ${e.mode} · ${e.kind} · evidencia de lectura relacional`;document.getElementById('evidenceQuote').textContent=`La relación se infiere al leer conjuntamente las menciones de “${s.name}” y “${t.name}” en el POT. La línea no inventa un componente: hace visible una dependencia o articulación que el documento deja distribuida entre capítulos y mapas.`;document.getElementById('evidenceSource').textContent='— RAPOT · inferencia documentada, verificar en el PDF';document.getElementById('mapList').innerHTML='<div class="map-card"><div><strong>PDF Bogotá Reverdece</strong><span>Usa la búsqueda del PDF para contrastar ambos conceptos.</span></div><a href="'+PDF+'" target="_blank">Abrir ↗</a></div>'}
document.querySelectorAll('.pill').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;render()}));
function applyTransform(){svg.querySelectorAll('g').forEach(g=>g.setAttribute('transform',`translate(${pan.x} ${pan.y}) scale(${pan.scale})`));const label=document.getElementById('zoomReset');if(label)label.textContent=Math.round(pan.scale*100)+'%'}
function resetView(){pan={x:0,y:0,scale:1,drag:false,sx:0,sy:0};applyTransform()}
document.getElementById('resetView').addEventListener('click',resetView);document.getElementById('zoomReset').addEventListener('click',resetView);document.getElementById('zoomIn').addEventListener('click',()=>{pan.scale=Math.min(1.8,pan.scale+.12);applyTransform()});document.getElementById('zoomOut').addEventListener('click',()=>{pan.scale=Math.max(.65,pan.scale-.12);applyTransform()});
svg.addEventListener('wheel',e=>{e.preventDefault();pan.scale=Math.max(.7,Math.min(1.7,pan.scale+(e.deltaY<0?.08:-.08)));applyTransform()},{passive:false});svg.addEventListener('pointerdown',e=>{pan.drag=true;pan.sx=e.clientX-pan.x;pan.sy=e.clientY-pan.y;svg.setPointerCapture(e.pointerId)});svg.addEventListener('pointermove',e=>{if(!pan.drag)return;pan.x=e.clientX-pan.sx;pan.y=e.clientY-pan.sy;applyTransform()});svg.addEventListener('pointerup',()=>pan.drag=false);
document.getElementById('mapsButton').addEventListener('click',()=>document.getElementById('cartografias').scrollIntoView({behavior:'smooth'}));
render();selectNode(nodes.find(n=>n.id==='humedales'));document.getElementById('nodeCount').textContent=nodes.length;document.getElementById('edgeCount').textContent=edges.length;
