document.addEventListener('DOMContentLoaded',()=>{
 const ranges=[['ecoRange','ecoValue'],['careRange','careValue'],['accessRange','accessValue']];
 const readout=document.getElementById('modelReadout');
 function update(){const vals=ranges.map(([id])=>Number(document.getElementById(id).value));ranges.forEach(([id,out])=>document.getElementById(out).textContent=document.getElementById(id).value+'%');document.querySelectorAll('[data-edge]').forEach(edge=>{const key=edge.dataset.edge;const value=key==='eco'?vals[0]:key==='care'?vals[1]:vals[2];edge.style.opacity=.15+value/125;edge.style.strokeWidth=1+value/45});let text=vals[1]>=vals[0]&&vals[1]>=vals[2]?'La hipótesis prioriza el cuidado de la vida cotidiana sin separar la movilidad de la estructura ecológica.':vals[0]>=vals[1]?'La hipótesis parte de una ciudad ecosistémica: el agua y la biodiversidad condicionan las demás decisiones.':'La hipótesis pone el acceso y la movilidad como puentes para conectar oportunidades, vivienda y servicios.';readout.innerHTML='<strong>Lectura actual</strong>'+text;}
 ranges.forEach(([id])=>document.getElementById(id).addEventListener('input',update));
 const texts={proximity:'¿Qué relaciones tendrían que fortalecerse para que la proximidad reduzca desigualdades sin aumentar la presión sobre los ecosistemas?',ecological:'¿Cómo puede una ciudad ecosistémica proteger el agua y la biodiversidad mientras garantiza vivienda, empleo y movilidad?',memory:'¿Cómo pueden los patrimonios y las memorias vivas orientar decisiones de cuidado, acceso y transformación urbana?'};
 document.querySelectorAll('[data-scenario]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-scenario]').forEach(b=>b.classList.toggle('active',b===btn));document.getElementById('scenarioText').textContent=texts[btn.dataset.scenario];document.querySelectorAll('[data-node]').forEach(n=>n.classList.toggle('active',n.dataset.node===btn.dataset.scenario||btn.dataset.scenario==='proximity'&&n.dataset.node==='care'));}));
 document.querySelectorAll('[data-node]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-node]').forEach(n=>n.classList.remove('active'));btn.classList.add('active');}));update();
});
